//Try Catch
try {
    autenticarUser()
} catch (error) {
    console.log(error);
}